# we use both C and C++, so advertize C++
language: cpp
sudo: false
addons:
  apt:
    packages:
    - intltool
    - libtool
    - libgtk2.0-dev
    - libgtk-3-dev
    - python-docutils
    # for docutils to support images
    - python-imaging
    - rst2pdf
    - doxygen
    # mingw -- FIXME: how to only install when MINGW=yes?
    - mingw-w64-tools
    - g++-mingw-w64-i686
    - gcc-mingw-w64-i686
    - binutils-mingw-w64-i686
compiler:
  - gcc
env:
  - GTK3=no
  - GTK3=yes
# extra matrix for cross compilation
matrix:
  include:
    - compiler: i686-w64-mingw32-gcc
      env: MINGW=yes GTK3=no
    - compiler: i686-w64-mingw32-gcc
      env: MINGW=yes GTK3=yes
before_script:
  - export CFLAGS="-g -O2 -Werror=pointer-arith -Werror=aggregate-return -Werror=implicit-function-declaration"
script:
  - >
    NOCONFIGURE=1 ./autogen.sh || exit 1;
    if [ -n "$MINGW" ]; then
      arg=-2; [ "$GTK3" = yes ] && arg=-3;
      unset CC CXX;
      sh ./scripts/cross-build-mingw.sh $arg;
    else
      mkdir _build                        &&
      cd _build                           &&
      ../configure --enable-gtk3=$GTK3    &&
      make -j2                            &&
      make -j2 check;
    fi
